[BRANDBOOK][SWE-1379] Created Input #done
senseteq-io/senseteq-brandbook-module pull request #20
Opened 2022-07-22 14:34 UTC by Anhelina4

2022-07-22 14:35 UTC, Anhelina4 commented
![image](https://user-images.githubusercontent.com/79013473/180462291-2b5e75cf-7597-4389-b446-cfd25d25602d.png)

2022-07-22 14:45 UTC, aleksandrgolyk approved these changes

2022-07-25 06:56 UTC, olenashevchuk requested changes

2022-07-25 06:56 UTC, olenashevchuk commented on src/app/components/elements/Input/Input.styled.js
>  export const InputWrapper = styled.div``
delete this useless wrapper

2022-07-25 06:56 UTC, olenashevchuk commented on src/styles/vars/input.css
> +  --brandbook-module-brand-input-placeholder-color-default: rgba(
are there no vars for  colors?

2022-07-25 06:56 UTC, olenashevchuk commented on src/styles/vars/input.css
> +  --brandbook-module-brand-input-border-radius: 7px;
use var --brandbook-module-brand-border-radius-default

2022-07-25 06:57 UTC, olenashevchuk commented on src/app/components/elements/Input/Input.js
>    const inputId = uuidv4()
we can use label prop like inputId

2022-07-25 07:28 UTC, Anhelina4 commented on src/styles/vars/input.css
> +  --brandbook-module-brand-input-placeholder-color-default: rgba(
No, this colot is not in config yet

2022-07-25 08:31 UTC, olenashevchuk commented on src/app/components/elements/Input/Input.js
> +        {...rest}
better pass rest object the last

2022-07-25 08:34 UTC, olenashevchuk approved these changes

2022-07-25 09:13 UTC, aleksandrgolyk approved these changes

2022-07-25 09:13 UTC, merged