[SWE-1389][BRANDBOOK MODULE] Start write greeting screen component #wip
senseteq-io/senseteq-brandbook-module pull request #23
Opened 2022-07-22 16:10 UTC by ArtemSuhoy

2022-07-24 19:37 UTC, olenashevchuk requested changes

2022-07-24 19:37 UTC, olenashevchuk commented on src/app/components/bundles/GreetingScreen/components/GreetingScreenInfo/GreetingScreenInfo.js
> +      <div>Divider</div>
you didn`t see workshop

2022-07-24 19:37 UTC, olenashevchuk commented on src/app/components/bundles/GreetingScreen/GreetingScreen.js
> +    <GreetingScreenContainer>
add Header and Footer

2022-07-26 07:14 UTC, Olexandr25 commented on src/app/components/bundles/GreetingScreen/GreetingScreen.js
> +  const { title, content } = props
add comment, what this component
- do
- what type of props, and for what
-

2022-07-26 12:30 UTC, olenashevchuk requested changes

2022-07-26 12:30 UTC, olenashevchuk commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +ExteriorScreenInfo.propTypes = {
add prop types

2022-07-26 12:30 UTC, olenashevchuk commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +          <Text variant="subtitle2">{subtitle}</Text>
strange

2022-07-26 12:30 UTC, olenashevchuk commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +      <Box pb={'32px'}>
use mb={4} instead pb={'32px'}>

2022-07-26 12:30 UTC, olenashevchuk commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +    <Col cw={11} v="bottom">
why 11? there is 10

2022-07-26 12:30 UTC, olenashevchuk commented on src/app/components/elements/Media/Img/Img.styled.js
> +`
wrong

2022-07-26 12:30 UTC, olenashevchuk commented on src/app/screens/Default/ClosingScreen/ClosingScreen.js
> +      title={'Thank you for watching!'}
delete {}

2022-07-26 12:30 UTC, olenashevchuk commented on src/app/screens/Default/OpeningScreen/OpeningScreen.js
> +    />
delete {}

2022-07-26 13:39 UTC, olenashevchuk approved these changes

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/bundles/ExteriorScreen/ExteriorScreen.js
> +   *  Used for first and last screen -- greeting and thanks
move comment above 
const ExteriorScreen = (prop) => {

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/bundles/ExteriorScreen/ExteriorScreen.js
> +  const decorationBgProps = {
move to __constants__

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/bundles/ExteriorScreen/ExteriorScreen.js
> +  const imageSrc = decoration === 'opening' ? 'ill-bg.svg' : 'ill-thx.svg'
leave comment, Why and For what result you do it

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenContainer/ExteriorScreenContainer.js
> +const ExteriorScreenContainer = (props) => {
write comment - js doc

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +const ExteriorScreenInfo = (props) => {
comment - js doc

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +import React from 'react'
do you need React here?

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/index.js
> +export { default } from './ExteriorScreenInfo'
change export

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/components/elements/Media/Img/Img.js
> +const Img = (props) => {
comment - js doc

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/screens/Default/ClosingScreen/ClosingScreen.js
> +const ClosingScreen = () => {
leave comment - for what this component

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/screens/Default/ClosingScreen/index.js
> +export { default } from './ClosingScreen'
check this export, it is a little strange

2022-07-27 14:19 UTC, Olexandr25 commented on src/app/screens/Default/OpeningScreen/OpeningScreen.js
> +const OpeningScreen = () => {
leave comment - what this component return

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/ExteriorScreen.js
> +      <PositionedContainer {...decorationBgProps[decoration]} zIndex="-10">
move zIndex into the decorationBgProps

put decorationBgProps outside of the ExteriorScreen function

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenContainer/ExteriorScreenContainer.js
> +      <Row height="100%" alignContent="center">
bad practice to use Row without Col right after

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +    <Col cw={10} v="bottom">
Bad practice to use Col without Row

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +      <Box pb={4}>
better to use margin for such cases

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +          <Title color="accent" variant="heading2">
bad practice to use H tag inside H tag. Use styled Text instead

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +      <Box pl={5}>
better to use margin

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/elements/Media/Img/Img.js
> +  src: PropTypes.string,
it should be required

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/elements/Media/Img/Img.js
> +  alt: PropTypes.string
it should be required

2022-07-27 15:42 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/components/ExteriorScreenInfo/ExteriorScreenInfo.js
> +  title: PropTypes.string,
it should be required

2022-08-02 13:45 UTC, alexpassss commented on src/app/components/bundles/ExteriorScreen/ExteriorScreen.js
> +    <ExteriorScreenStyled>
Seems that this component will be reusable across all screens

2022-08-02 13:54 UTC, merged