[DIVIDER-COMPONENT] [SWE-1358] create divider component
senseteq-io/senseteq-brandbook-module pull request #24
Opened 2022-07-22 16:17 UTC by whoiam460

2022-07-22 16:39 UTC, aleksandrgolyk approved these changes

2022-07-24 19:41 UTC, olenashevchuk requested changes

2022-07-24 19:41 UTC, olenashevchuk commented on src/app/components/elements/Divider/Divider.styled.js
> +  ${(props) => {
use one variant of destructuring , better write ${({color})}... in styled-component file

2022-07-24 19:41 UTC, olenashevchuk commented on src/app/components/elements/Divider/Divider.js
> +  return <DividerStyled bold={bold} color={color} length={length} />
do we need a bold prop?

2022-07-24 19:41 UTC, olenashevchuk commented on src/app/components/elements/Divider/Divider.js
> +  return <DividerStyled bold={bold} color={color} length={length} />
better use size prop instead length

2022-07-25 07:34 UTC, whoiam460 commented on src/app/components/elements/Divider/Divider.js
> +  return <DividerStyled bold={bold} color={color} length={length} />
yes because we have two width of divider one withd will be default and second when you wride bold it will be second width

2022-07-25 07:50 UTC, olenashevchuk commented on src/app/components/elements/Divider/Divider.styled.js
> +  `
use vars

2022-07-25 07:50 UTC, olenashevchuk commented on src/app/components/elements/Divider/Divider.styled.js
> +}
use vars

2022-07-25 07:59 UTC, olenashevchuk commented on src/app/components/elements/Divider/Divider.styled.js
> +
delete {}

2022-07-25 08:12 UTC, olenashevchuk commented on src/styles/vars/divider.css
> +    --brandbook-divider-height-xs: 96px;
wrong name for vars

2022-07-25 08:28 UTC, olenashevchuk approved these changes

2022-07-25 08:29 UTC, merged