Task swe 1445 create alphabet secondary screen
senseteq-io/senseteq-brandbook-module pull request #37
Opened 2022-07-25 15:26 UTC by whoiam460

2022-07-25 15:35 UTC, olenashevchuk approved these changes

2022-07-26 07:20 UTC, Olexandr25 commented on src/app/components/bundles/ContentScreen/components/ContentScreenContent/ContentScreenContent.js
> +    <Col pl={136} mt={60} cw={8}>
don't move Col
move Box inside Col

2022-07-26 07:20 UTC, Olexandr25 commented on src/app/components/bundles/ContentScreen/components/ContentScreenInfo/ContentScreenInfo.js
> +    <Col mt={60} p={0} cw={4}>
the same

2022-07-26 07:20 UTC, Olexandr25 commented on src/app/screens/Typography/TypographyContent/SecondaryScreen.js
> +    <>
useless Fragment

2022-07-26 09:33 UTC, aleksandrgolyk requested changes

2022-07-26 09:33 UTC, aleksandrgolyk commented on src/app/components/bundles/ContentScreen/components/ContentScreenContainer/ContentScreenContainer.styled.js
> +  margin-left: 96px;
is it possible not to use this strict value ? what will be with yours template on another mediasizes ?

2022-07-26 09:33 UTC, aleksandrgolyk commented on src/app/components/bundles/ContentScreen/components/ContentScreenContent/ContentScreenContent.js
> +      <Box mt={4} pl={136}>
is it possible not to use this strict value? what will be with your template on other media sizes ?

2022-07-26 09:33 UTC, aleksandrgolyk commented on src/styles/vars/grid.css
> +    --brandbook-module-grid-gutter-xxl: 16px;
xl and xxl are the same? looks like typing error ?

2022-07-26 09:41 UTC, Olexandr25 commented on src/app/components/bundles/ContentScreen/components/ContentScreenContent/ContentScreenContent.js
> +      <Box mt={4} pl={136}>
At this moment, we have strict values of screen, and work with them

2022-07-26 10:39 UTC, whoiam460 commented on src/app/components/bundles/ContentScreen/components/ContentScreenContainer/ContentScreenContainer.styled.js
> +  margin-left: 96px;
now we dont have responsive and different media size just this strict value

2022-07-26 14:51 UTC, aleksandrgolyk approved these changes

2022-07-27 10:56 UTC, merged