[SWE-1199] [BRANDBOOK] GreetingScreen #wip
senseteq-io/senseteq-brandbook-module pull request #4
Opened 2022-07-19 11:57 UTC by AnastasiaShapowalova

<img width="1680" alt="Screenshot 2022-07-19 at 14 56 55" src="https://user-images.githubusercontent.com/87419953/179744625-0af0b6ff-fcd8-4ec5-9ad4-321de6467632.png">

2022-07-19 18:37 UTC, AnastasiaShapowalova commented
1 Merged with development, resolved conflicts
2 Fix Header component
3 Add footer to screen
4 Add rectangle

2022-07-19 21:51 UTC, AnastasiaShapowalova commented
1 Reduced Img component
2 Add vars to Header component
3 Add params

2022-07-20 08:13 UTC, olenashevchuk requested changes

2022-07-20 08:15 UTC, olenashevchuk commented on src/App.js
> +import Greeting from 'assets/hello.png'
not a suitable name for image

2022-07-20 08:26 UTC, GingerBoy14 requested changes

2022-07-20 08:26 UTC, GingerBoy14 commented on src/components/layouts/GreetingScreen/GreetingScreen.styled.js
> +const RectangleStyled = styled(Text)`
what with naming, what mean rectangle = styled(**Text**)...

2022-07-20 08:47 UTC, AnastasiaShapowalova commented
1 Delete image component and make styled for image in GreetingScreen
2 Add alt to image
3 Fix ReactangleStyled
4 Fix image naming

2022-07-20 13:51 UTC, AnastasiaShapowalova commented on src/components/layouts/GreetingScreen/GreetingScreen.js
> +    []
not one warnings in console

2022-07-21 07:25 UTC, olenashevchuk approved these changes

2022-07-21 07:25 UTC, merged