[SWE-1475] [BRANDBOOK] Check fontFamily in Alphabet #done
senseteq-io/senseteq-brandbook-module pull request #42
Opened 2022-07-26 08:59 UTC by AnastasiaShapowalova

<img width="508" alt="Screenshot 2022-07-26 at 11 36 53" src="https://user-images.githubusercontent.com/87419953/180967239-90fd6157-17cb-4986-9123-1eaabab2cca7.png">

2022-07-26 09:02 UTC, olenashevchuk approved these changes

2022-07-26 14:16 UTC, olenashevchuk requested changes

2022-07-26 14:16 UTC, olenashevchuk commented on src/app/screens/Typography/TypographyContent/SecondaryScreen.js
> +      pageNumber={'09'}
Delete {}

2022-07-26 14:16 UTC, olenashevchuk commented on src/styles/vars/index.css
> +@import url('./contentScreen.css');
see above

2022-07-26 15:10 UTC, olenashevchuk approved these changes

2022-07-27 14:28 UTC, Olexandr25 commented on src/app/components/bundles/ContentScreen/ContentScreen.js
>  const ContentScreen = (props) => {
try to leave here comment - js doc

2022-07-27 14:28 UTC, Olexandr25 commented on src/app/components/bundles/ContentScreen/components/ContentScreenContent/ContentScreenContent.js
>  const ContentScreenContent = (props) => {
comment - js doc

2022-07-27 14:28 UTC, Olexandr25 commented on src/app/components/bundles/ContentScreen/components/ContentScreenInfo/ContentScreenInfo.js
>  const ContentScreenInfo = (props) => {
comment - js doc

2022-07-27 14:28 UTC, Olexandr25 commented on src/app/components/elements/Alphabet/Alphabet.js
>  const Alphabet = (props) => {
comment - js doc

2022-07-27 14:28 UTC, Olexandr25 commented on src/app/screens/Iconography/IconographyContent/IconographyExamples/IconographyExamples.js
> +import React from 'react'
do you need here React?

2022-07-27 14:28 UTC, Olexandr25 commented on src/app/screens/Iconography/IconographyContent/IconographyExamples/IconographyExamples.js
> +const IconographyExamples = () => {
comment - js doc

2022-07-27 14:28 UTC, Olexandr25 commented on src/app/screens/Typography/TypographyContent/SecondaryScreen.js
> +const SecondaryScreen = () => {
comment - js doc

2022-07-27 14:50 UTC, whoiam460 commented on src/app/components/elements/Alphabet/Alphabet.js
>        <Text variant="brand-alphabet" fm={fontFamily}>
first merge development inside this branch pr dev have important changes

2022-07-27 18:31 UTC, closed without merging