Task swe 1499 rewrite alphabet primary screen
senseteq-io/senseteq-brandbook-module pull request #48
Opened 2022-07-26 12:27 UTC by whoiam460

2022-07-26 12:35 UTC, olenashevchuk commented on src/app/components/bundles/ContentScreen/ContentScreen.js
> +    <>
useless <>

2022-07-26 12:35 UTC, olenashevchuk commented on src/app/components/bundles/ContentScreen/components/ContentScreenContainer/ContentScreenContainer.styled.js
> +  margin-left: var(--brandbook-module-content-screen-margin-left);
!!!!

2022-07-26 12:35 UTC, olenashevchuk commented on src/app/screens/Typography/TypographyContent/SecondaryScreen.js
> +      pageNumber={'09'}
delete {}

2022-07-26 12:35 UTC, olenashevchuk commented on src/styles/vars/contentScreen.css
> +    --brandbook-module-content-screen-margin-left: 96px;
!!!!!!!!!!!

2022-07-26 12:48 UTC, Slavka406 requested changes

2022-07-26 12:48 UTC, Slavka406 commented on src/app/screens/Typography/TypographyContent/PrimaryScreen.js
> +      pageNumber={'09'}
?

2022-07-26 12:48 UTC, Slavka406 commented on src/app/screens/Typography/TypographyContent/PrimaryScreen.js
> +          <Alphabet ff="primary" />
???

2022-07-26 12:48 UTC, Slavka406 commented on src/app/components/elements/Alphabet/Alphabet.js
> +  const { fontFamily } = props
????

2022-07-26 12:48 UTC, Slavka406 commented on src/app/components/elements/Alphabet/Alphabet.js
>        <Text variant="brand-alphabet" fm={fontFamily}>
???

2022-07-27 14:33 UTC, Olexandr25 commented on src/app/screens/Typography/TypographyContent/PrimaryScreen.js
> +const PrimaryScreen = () => {
write comment about this component
what return and for what it

2022-08-02 13:08 UTC, closed without merging