Task [SWE-1200] create contentscreen
senseteq-io/senseteq-brandbook-module pull request #5
Opened 2022-07-20 09:12 UTC by Olexandr25

- Wrote ContentScreen
- Wrote typography

![Screenshot 2022-07-20 at 12 07 41](https://user-images.githubusercontent.com/36109776/179944120-4c237e3c-4a58-47c9-a5f7-8de0b308424f.png)

2022-07-20 09:26 UTC, aleksandrgolyk commented on src/components/screens/Content/ContentScreen.js
> +      style={{ height: '384px' }}
is it necessary to use strict px numbers?

2022-07-20 09:32 UTC, Olexandr25 commented on src/components/screens/Content/ContentScreen.js
> +      style={{ height: '384px' }}
I do not know. I took this height from figma

2022-07-20 09:46 UTC, olenashevchuk commented on src/components/screens/Content/ContentScreen.js
> +        </div>
don't use styled-components, expand the component Title and Text with appropriate props

2022-07-21 08:09 UTC, olenashevchuk commented on src/components/elements/Typography/Text/Text.js
>      }),
wrong

2022-07-21 08:38 UTC, 5P4C3GR33D approved these changes

2022-07-21 08:59 UTC, aleksandrgolyk approved these changes

2022-07-21 10:26 UTC, Olexandr25 commented
<img width="1440" alt="Screenshot 2022-07-21 at 13 20 12" src="https://user-images.githubusercontent.com/36109776/180192325-00a582e0-7574-463b-ad54-582e86354305.png">

2022-07-21 10:51 UTC, olenashevchuk requested changes

2022-07-21 10:51 UTC, olenashevchuk commented on src/components/elements/Typography/Text/Text.js
> +    style: { style, ...rest },
delete this prop

2022-07-21 10:51 UTC, olenashevchuk commented on src/components/elements/Typography/Title/Title.js
> +
what it is? add comment, move to appropriate part of component

2022-07-21 10:51 UTC, olenashevchuk commented on src/components/elements/Typography/Title/Title.js
> +
it can be simplified

2022-07-21 10:51 UTC, olenashevchuk commented on src/components/layouts/Screen/Screen.js
> +    <ScreenStyled bg={bgColor} className="container-fluid">
I think , instead "bg" prop better to use "dark" prop, because we have only 2 type of screen's background (dark, light)

2022-07-21 10:51 UTC, olenashevchuk commented on src/screens/Content/ContentScreen.js
> +    <div style={{ marginTop: '96px' }}>
styles must be in appropriated file

2022-07-21 10:51 UTC, olenashevchuk commented on src/styles/vars/screen.css
> +  --brandbook-module-screen-header-mb: 64px;
do you use --brandbook-module-screen-header-mb var?

2022-07-21 10:51 UTC, olenashevchuk commented on src/styles/vars/screen.css
> +  --brandbook-module-screen-body-m: 64px 112px;
better use full name for prop margin. "m" is no informative

2022-07-21 10:51 UTC, olenashevchuk commented on src/styles/vars/theme.light.css
> +    --brandbook-module-typography-color-primary
for brand and presentation vars we use 1 file (for the present), but we need to separate this vars

2022-07-21 10:51 UTC, olenashevchuk commented on src/styles/vars/theme.light.css
> +    --brandbook-module-typography-color-primary
why do you use presentation var for title of brand?

2022-07-21 10:54 UTC, Olexandr25 commented on src/styles/vars/screen.css
> +  --brandbook-module-screen-header-mb: 64px;
yes, inside component Screen, there is breadcrumb, and on every screen there are 
mb:64px

2022-07-21 13:31 UTC, closed without merging