Task swe 1602 change vars naming
senseteq-io/senseteq-brandbook-module pull request #60
Opened 2022-07-27 15:53 UTC by AnastasiaShapowalova

2022-07-27 19:25 UTC, BogdanovJn commented on src/styles/vars/theme.light.css
> +  --neutral-inverse: rgba(37, 48, 55, 0.64);
Same to --white-inverse

2022-07-27 20:13 UTC, BogdanovJn commented on src/styles/vars/input.css
> +  --input-active-box-shadow: 0px 0px 0px 2px var(--primary);
Looks like mistake, I can't find variable "--primary"

2022-07-27 20:13 UTC, BogdanovJn commented on src/styles/vars/header.css
> +  --header-text-white: var(--senseteq-white);
What the difference between "--white" and "--senseteq-white"?

2022-07-27 20:13 UTC, BogdanovJn commented on src/styles/index.css
> +  --senseteq-text-fw-semi-bold: 600;
semibold

2022-07-27 20:13 UTC, BogdanovJn commented on src/styles/index.css
> +  --senseteq-white: rgb(255, 255, 255);
Inconsistency with "--senseteq-accent", "--senseteq-neutral" and "--senseteq-white" (
find the error yourself)

2022-07-27 20:13 UTC, BogdanovJn commented on src/app/domains/Iconography/components/IconView/IconView.styled.js
> +  width: var(--icon-view-width);
Not sure with width, check grid in the Figma

2022-07-27 20:22 UTC, AnastasiaShapowalova commented on src/styles/vars/theme.light.css
> +  --white: rgb(255, 255, 255);
When we make shades we add alpha as a var(). I thought that we should write the main coulors as RGB in this case. Isn't that the point?

2022-07-28 06:52 UTC, alexpassss requested changes

2022-07-28 06:52 UTC, alexpassss commented on src/app/components/elements/Chapter/Chapter.styled.js
> +  border-bottom: 1px solid var(--white);
Borders also should be moved to the base vars

2022-07-28 06:52 UTC, alexpassss commented on src/app/components/elements/Divider/Divider.styled.js
> +    background-color: var(--divider-accent-bg);
Same issue with objects

2022-08-01 08:23 UTC, closed without merging