[ERRORS ON DEV][SWE-1635] Fixed errors on development - rewrote ind…
senseteq-io/senseteq-brandbook-module pull request #63
Opened 2022-07-28 09:10 UTC by Anhelina4

…exes and file-names #done

2022-07-29 07:05 UTC, alexpassss requested changes
Same mistakes across PR

2022-07-29 07:05 UTC, alexpassss commented on src/app/screens/AppIcon/screens.js
> +import { default as AppIconAndroidScreen } from './AppIconContent/AppIconAndroid/AppIconAndroidScreen'
Bad import

2022-07-29 07:05 UTC, alexpassss commented on src/app/screens/Color/screens.js
> +import { default as ColorIntroScreen } from './ColorIntro/ColorIntroScreen'
Same here

2022-07-29 07:05 UTC, alexpassss commented on src/app/screens/Elements/screens.js
> +import { default as ElementsIntroScreen } from './ElementsIntro/ElementsIntroScreen'
Same here

2022-07-29 07:05 UTC, alexpassss commented on src/app/screens/Elements/screens.js
> +import { default as ElementsIntroScreen } from './ElementsIntro/ElementsIntroScreen'
Strange file name

2022-07-29 07:39 UTC, Anhelina4 commented on src/app/screens/Elements/screens.js
> +import { default as ElementsIntroScreen } from './ElementsIntro/ElementsIntroScreen'
What name should I use instead? I was consulting with Olena and Maks and they suggested that name. It is a file which contain all screens related to a topic(Typography, Imagery, App Icon) in correct order: Intro and then all the screen with content

2022-08-01 08:36 UTC, alexpassss approved these changes

2022-08-01 08:44 UTC, merged