[CHECKBOX][SWE-1673] Write checkbox component
senseteq-io/senseteq-brandbook-module pull request #67
Opened 2022-07-28 15:32 UTC by Olexandr25

<img width="755" alt="Screenshot 2022-07-28 at 18 23 50" src="https://user-images.githubusercontent.com/36109776/181577803-fd00734f-bb74-4fee-80ee-ee5d08a56f01.png">

2022-07-28 15:37 UTC, alexpassss requested changes

2022-07-28 15:37 UTC, alexpassss commented on src/app/components/elements/Checkbox/Checkbox.styled.js
> +  border-radius: var(--br-radius);
br-radius??

2022-07-28 15:37 UTC, alexpassss commented on src/app/components/elements/Checkbox/Checkbox.styled.js
> +      color: rgba(var(--neutral), var(--alpha-4));
Should be moved to the checkbox related var

2022-07-28 15:37 UTC, alexpassss commented on src/app/components/elements/Checkbox/Checkbox.styled.js
> +  font-size: var(--brandbook-module-text-body1-fs);
Fix var naming

2022-07-28 15:37 UTC, alexpassss commented on src/app/components/elements/Checkbox/Checkbox.vars.module.css
> +    --default-checked-bg:  rgba(var(--accent), var(--alpha-1)); /* 1 */
Where is mediator?

2022-07-28 15:37 UTC, alexpassss commented on src/app/components/elements/Checkbox/Checkbox.vars.module.css
> +    --hover-checked-bg: rgba(var(--accent), var(--alpha-2)); /* 0.72 */
Everything related to the colors should be inside global theme.css

2022-07-29 10:22 UTC, alexpassss commented on src/app/components/elements/Checkbox/Checkbox.styled.js
> +  color: var(--checkbox-text-color);
--checkbox-color

2022-07-29 10:22 UTC, alexpassss commented on src/app/components/elements/Checkbox/Checkbox.vars.module.css
> +    --checkbox-checked-bg-default: var(--action-accent-default);
everything related to the colors should be moved to the theme file

2022-08-01 09:16 UTC, Olexandr25 commented
<img width="391" alt="Screenshot 2022-08-01 at 12 11 53" src="https://user-images.githubusercontent.com/36109776/182115983-d606b557-de89-45c1-9ead-4a5918b4eeb3.png">

2022-08-01 15:03 UTC, alexpassss approved these changes

2022-08-01 15:03 UTC, merged