[CONFIG] [SWE-1641] Change config #wip
senseteq-io/senseteq-brandbook-module pull request #68
Opened 2022-07-28 19:21 UTC by AnastasiaShapowalova

2022-07-28 19:39 UTC, AnastasiaShapowalova commented
1 Change all namings
2 Make some namings shorter
3 Change hex to rgba
4 Fix main typography

2022-07-28 22:09 UTC, Anhelina4 commented on src/styles/vars/typography.css
> +  --font-family-maket: 'AbrilFatface', sans-serif;
odd naming
primary - for items we use often, secondary - for titles. Font-family-maket is for what?

2022-07-28 22:09 UTC, Anhelina4 commented on src/styles/vars/typography.css
> +  --font-family-maket: 'AbrilFatface', sans-serif;
We were talking that all font-families have to be Galano for now

2022-07-28 22:09 UTC, Anhelina4 commented on src/styles/vars/typography.css
> +  --font-family-primary: 'PlusJakartaSans', sans-serif;
same with ff value

2022-07-28 22:09 UTC, Anhelina4 commented on src/styles/vars/typography.css
> +  --font-family-secondary: 'GalanoGrotesque', sans-serif;
I guess we should add a var with presentation font-family(because in all brand-screens we have elements which remains in senseteq-design-styling, like header and footer)

2022-07-29 05:42 UTC, AnastasiaShapowalova commented on src/styles/vars/theme.light.css
> +  --black-t-lighten5: rgba(var(--black), var(--alpha-5));
<img width="621" alt="Screenshot 2022-07-29 at 08 42 04" src="https://user-images.githubusercontent.com/87419953/181690578-d75a83b9-c7ec-43b6-8069-08e71857c87c.png">

2022-07-29 05:43 UTC, AnastasiaShapowalova commented on src/styles/vars/typography.css
> +  --font-family-maket: 'AbrilFatface', sans-serif;
It is third font family we have. What name should i give?

2022-07-29 06:45 UTC, AnastasiaShapowalova commented on src/styles/vars/typography.css
> +  --font-family-secondary: 'GalanoGrotesque', sans-serif;
we have font families in root(for main part of presentation) and font family in senseteq class

2022-07-29 08:18 UTC, AnastasiaShapowalova commented on src/app/components/elements/Chapter/Chapter.styled.js
> +  padding-bottom: var(--chapter-py);
it will be fixed by another person on their branch

2022-07-29 08:18 UTC, AnastasiaShapowalova commented on src/styles/vars/divider.css
> +  --divider-semibold-width: 4px;
it will be fixed by another person on their branch

2022-07-29 10:16 UTC, alexpassss requested changes

2022-07-29 10:16 UTC, alexpassss commented on src/app/components/bundles/IntroScreen/IntroScreen.styled.js
> +  background: var(--neutral-bg);
not sure if var is correct

2022-07-29 10:19 UTC, Olexandr25 commented on src/app/components/bundles/IntroScreen/IntroScreen.styled.js
> +  background: var(--neutral-bg);
Did you mean this variant of var?

--intro-screen-bg-default: var(--neutral-bg);

2022-08-01 08:08 UTC, alexpassss approved these changes

2022-08-01 08:08 UTC, alexpassss commented on src/app/components/elements/Button/Button.styled.js
> +  font-size: var(--btn-text-fs);
btn-fs

2022-08-01 08:08 UTC, alexpassss commented on src/app/components/elements/Button/Button.styled.js
> +  font-family: var(--text-ff);
btn-ff

2022-08-01 08:08 UTC, alexpassss commented on src/app/components/elements/Typography/Title/Title.styled.js
> +    font-family: var(--ff-primary);
title-ff (optional)

2022-08-01 08:21 UTC, merged